#backend:
  #image: node:6.5
  #command: npm run dev
  #volumes:
    #- ./src/backend/:/app
  #working_dir: /app
  #ports:
    #- "8080:8080"

frontend:
  image: node:6.5
  command: npm run dev
  volumes:
    - ./frontend/:/app
  working_dir: /app
  ports:
    - "4000:4000"
