version: '2'
services:
  backend:
    image: node:6.5
    command: npm run dev
    volumes:
      - ./backend/:/app
    environment:
      NODE_ENV: development
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: node:6.5
    command: npm run dev
    volumes:
      - ./frontend/:/app
    working_dir: /app
    ports:
      - "4000:4000"

  db:
    image: mongo:3.2
    ports:
      - "27017:27017"
